media:
  input: public/assets
  output: /assets
  categories: ["image"]
content:
  - name: posts
    label: Nieuws
    type: collection
    path: _posts
    view:
      fields: [coverImage, title, date]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: excerpt, label: Excerpt, type: string }
      - { name: coverImage, label: Cover image, type: image }
      - {
          name: date,
          label: Date,
          type: date,
          options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
        }
      - name: author
        label: Author
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
      - name: ogImage
        label: Image (social sharing)
        type: object
        fields:
          - { name: url, label: URL, type: image }
      - { name: body, label: Body, type: rich-text }
  - name: fotoAlbum
    label: Foto Album
    type: collection
    path: _foto-album
    view:
      fields: [coverImage, title, url]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: url, label: Url, type: string, required: true }
      - { name: coverImage, label: Cover image, type: image }
      - {
          name: date,
          label: Date,
          type: date,
          options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
        }
  - name: sponsors
    label: Sponsors
    type: collection
    path: _sponsors
    view:
      fields: [logo, name, siteUrl]
    fields:
      - { name: name, label: Title, type: string, required: true }
      - { name: siteUrl, label: Site Url, type: string, required: true }
      - { name: logo, label: Logo image, type: image, required: true }
      - {
          name: date,
          label: Date,
          type: date,
          options: { time: true, format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
        }
      - name: imageColourBehaviour
        label: image Colour Behaviour
        type: select
        options:
          values: [Normal, InvertedLight, InvertedDark, Inverted]
